---
kind: pipeline
type: docker
name: default

steps:
- name: APIsec scan trigger
  image: ubuntu
  commands:
  - apt update
  - apt install -y curl jq wget
  - wget https://raw.githubusercontent.com/apisec-inc/apisec-scripts/master/apisec_job_invoke_script.sh?token=AVOLEQ4FVVPJJ3DPAME4JELBS56SI -O apisec_job_invoke_script.sh;bash apisec_job_invoke_script.sh --host https://developer.apisec.ai --username ${{ secrets.username }} --password ${{ secrets.password }} --project "nerwersdfprject" --profile Master --scanner Super_1 --emailReport true --reportType RUN_SUMMARY
  - echo "Script execition is finished"
